### ISSUE TITLE
Clear everything when the number is between 0 and 7 

### ISSUE THREAD

**Issue by fcoterroba** [fcoterroba/Funny_DNI_letter#13]
Hey, another little issue:

When the user enters the number of his DNI (which must have 8 digits), the letter is displayed, and the famous random but I want to clear everything if the user delete a number.

In summary, if the user deletes a digit or writes more numbers, I want to delete everything, the letter and all the information of the famous.

It would be fine, if possible, to prohibit the user from typing more than 8 digits and hide the arrows of the input number and disable the up/down number with arrows or scroll.

**Comment by irfanukani** [comment]
Hi, Do you need to clear all numbers every time backspace gets a hit?

**Comment by irfanukani** [comment]
Please can you check my merge request..

**Comment by fcoterroba** [comment]
Hey. Your PR looks good but please, you modify a lot of spaces. Please do it again but don't modify the space of old code #14

**Comment by irfanukani** [comment]
I've resolved the conflicts. check now...

**Comment by fcoterroba** [comment]
Merged! Thanks
