### ISSUE TITLE
Change the style (dark and light modes)

### ISSUE THREAD

**Issue by fcoterroba** [fcoterroba/Funny_DNI_letter#16]
Hey!

I want do two main things:

- **Light mode**: Change the header and footer bg-color to green (I let you select the green exactly)
- **Dark mode**: Obviusly, change the body color to dark (You choose dark #000 or another one) just keep in mind choose something which fix with the previous green

You'll need to detect if the user theme is black or light and choose one of them.
You can make another CSS to dark-style or keep in the same
If you think you got another color matching perfect in light mode, change it instead standard white

**Comment by fcoterroba** [comment]
Hey @williamroberttv thanks you for your PR #17 but please, next time ask for first and I assignee it to you. We do this to keep some order because right now your PR is in conflict with main.

**Comment by williamroberttv** [comment]
Of course friend, apologies

**Comment by fcoterroba** [comment]
You rock! Thanks again for the PR. Is merged! #17
