### ISSUE TITLE
Fix the footer to the bottom

### ISSUE THREAD

**Issue by fcoterroba** [fcoterroba/Funny_DNI_letter#2]
Like you can see in the [demo](https://fcoterroba.github.io/Funny_DNI_letter/) the footer isn't fixed at the bottom.

With this issue you'll fix the footer always to the bottom.

Remember in this project we're using [materializecss.com](https://materializecss.com/)

**Comment by zclut** [comment]
I can fix the footer, could you assign me this issue? I will PR it on October

**Comment by fcoterroba** [comment]
Hey @zclut ! Of course, you can do it. I'll assignee it to you and will wait to your October PR.
