### ISSUE TITLE
Add "fork me on github" ribbon

### ISSUE THREAD

**Issue by fcoterroba** [fcoterroba/Funny_DNI_letter#8]
Hey! I'm proud to use GitHub and I want show it to the world. So, I want add a typical ribbon on top-rigth like this:

![image](https://user-images.githubusercontent.com/46996764/135815490-b9845dba-afa1-40d2-8e40-806ad75bb07c.png)

Please, be a little creative, you can add a Octocat when you hover it or add a funny gif or something. Feel free to expand your creativeness. Keep in mind the mobile version

**Comment by Deepak91168** [comment]
Will you please explain where to add this ribbon on the web page

**Comment by Deepak91168** [comment]
Hey @fcoterroba I'm interested please assign it to me!
 
![image](https://user-images.githubusercontent.com/78257493/135816863-f9e3566d-a7bc-40bf-a9a0-1716cc0e95ad.png)

You want it on top-right with some creativity
I'm ready to go !

**Comment by fcoterroba** [comment]
All yours. What do you got in mind to do?

**Comment by Deepak91168** [comment]
As I can see page is quite easy on eyes I would like to use such colors and hovering effects too.
I will come up with **PR** ASAP.
