### ISSUE TITLE
Add a footer text with number of contributors

### ISSUE THREAD

**Issue by fcoterroba** [fcoterroba/Funny_DNI_letter#9]
Hey! I want change the "fcoterroba" text on the footer to:

Open source from [@fcoterroba](https://fcoterroba.com) and XX persons

Change the XX for the number of persons by the actual contributors at this moment and href with `_blank` to [here](https://github.com/fcoterroba/Funny_DNI_letter/graphs/contributors). You can scrappy it or use whatever you want.

**Comment by nirmalKumawat-kgp** [comment]
I am interested in it

**Comment by fcoterroba** [comment]
All yours

**Comment by nirmalKumawat-kgp** [comment]
> All yours

thanks

**Comment by nirmalKumawat-kgp** [comment]
can you add hacktoberfest-accepted label
